# Spring Properties
spring:
  application:
    name: service02

info:
  app:
    name: service02
    description: mountain ascent
    version: 1.0.0

# Discovery Server Access
eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka
  instance:
        preferIpAddress: true
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        leaseRenewalIntervalInSeconds: 100
        leaseExpirationDurationInSeconds: 200
# HTTP Server
server:
  port: 8085  
    