# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  #server:
  #  enableSelfPreservation: false 
  #  eviction-interval-timer-in-ms: 1000
server:
  port: 1111   # HTTP (Tomcat) port 